var timezones = {
  "−12.00": [
    "United States Minor Outlying Islands",
    "Baker Island",
    "Howland Island"
  ],
  "−11.00": [
    "United States",
    "American Samoa",
    "Hawaii",
    "French Frigate Shoals and all of the Northwestern Hawaiian Islands located further west",
    "United States Minor Outlying Islands",
    "Jarvis Island",
    "Kingman Reef",
    "Midway Atoll",
    "Palmyra Atoll",
    "New Zealand",
    "Niue"
  ],
  "−10.00": [
    "France",
    "French Polynesia (except Marquesas Islands and Gambier Islands)",
    "New Zealand",
    "Cook Islands",
    "United States (Hawaii-Aleutian Time Zone)",
    "Alaska",
    "Aleutian Islands west of 169.30°W",
    "Hawaii",
    "As far west as Necker Island",
    "United States Minor Outlying Islands",
    "Johnston Atoll"
  ],
  "−09.30": [
    "France",
    "French Polynesia",
    "Marquesas Islands"
  ],
  "−09.00": [
    "France",
    "French Polynesia",
    "Gambier Islands",
    "United States (Alaska Time Zone)",
    "Alaska",
    "Except Aleutian Islands west of 169.30°W"
  ],
  "−08.00": [
    "Canada (Pacific Time Zone)",
    "British Columbia",
    "Except the south-eastern communities of Cranbrook",
    " Golden and Invermere",
    "Yukon",
    "France",
    "Clipperton Island",
    "Mexico",
    "Baja California",
    "United Kingdom",
    "Pitcairn Islands",
    "United States (Pacific Time Zone)",
    "California",
    "Idaho",
    "North of Salmon River",
    "Nevada (except West Wendover)",
    "Oregon",
    "All of the state except Malheur County (but including a small strip in the south of Malheur)",
    "Washington"
  ],
  "−07.00": [
    "Canada (Mountain Time Zone)",
    "Alberta",
    "British Columbia",
    "The south-eastern communities of Cranbrook",
    " Golden and Invermere",
    "Northwest Territories",
    "Nunavut",
    "Kitikmeot Region",
    "Saskatchewan",
    "Lloydminster",
    "Mexico",
    "Baja California Sur",
    " Chihuahua",
    " Nayarit",
    " Sinaloa and Sonora states",
    "United States (Mountain Time Zone)",
    "Arizona",
    "Colorado",
    "Idaho",
    "South of Salmon River",
    "Kansas",
    "The western counties of Greeley",
    " Hamilton",
    " Sherman and Wallace",
    "Montana",
    "Nebraska",
    "The western counties of Cherry (western part)",
    " Hooker",
    " Arthur",
    " Keith",
    " Perkins",
    " Chase and Dundy",
    " and all counties to the west of these",
    "Nevada",
    "West Wendover",
    "New Mexico",
    "North Dakota",
    "The Southwestern counties of Adams",
    " Billings",
    " Bowman",
    " Dunn (southern part)",
    " Golden Valley",
    " Grant",
    " Hettinger",
    " McKenzie (southern part)",
    "Sioux (west of ND route 31)",
    " Slope and Stark",
    "Oregon",
    "Malheur County (except a small strip in the south)",
    "South Dakota",
    "The western counties of Corson",
    " Dewey",
    " Stanley (western part)",
    " Jackson and Bennett",
    " and all counties to the west of these",
    "Texas",
    "The western counties of Culberson (northwestern part)",
    " El Paso and Hudspeth",
    "Utah",
    "Wyoming"
  ],
  "−06.00": [
    "Belize",
    "Canada (Central Time Zone)",
    "Manitoba",
    "Nunavut",
    "Kivalliq Region except Southampton Island (Coral Harbour)",
    "Northwestern Ontario (West of 90° West, except Atikokan area, New Osnaburgh and Pickle Lake area, Shebandowan and Upsala area, and Big Trout Lake area east of 90° West)",
    "Saskatchewan",
    "All province except Lloydminster",
    "Chile",
    "Easter Island",
    "Costa Rica",
    "Ecuador",
    "Galápagos Islands",
    "El Salvador",
    "Guatemala",
    "Honduras",
    "Mexico",
    "All of the country except the states of Baja California",
    " Baja California Sur",
    " Chihuahua",
    " Nayarit",
    "Sinaloa and Sonora.",
    "Nicaragua",
    "United States (Central Time Zone)",
    "Alabama",
    "Entire state except Phenix City",
    "Arkansas",
    "Florida",
    "West of the Apalachicola River",
    " except for the portions of Franklin County and Gulf County south of the Intracoastal Waterway",
    "Illinois",
    "Indiana",
    "Northwestern counties of Jasper",
    " Lake",
    " LaPorte",
    " Newton",
    " Porter and Starke",
    "Southwestern counties of Gibson",
    " Perry",
    " Posey",
    " Spencer",
    " Vanderburgh and Warrick",
    "Iowa",
    "Kansas",
    "Entire state except westernmost counties",
    "Kentucky",
    "The counties of Breckenridge",
    " Grayson",
    " Hart",
    " Green",
    " Adair",
    " Russell and Clinton",
    " and all counties to the west of these",
    "Louisiana",
    "Michigan",
    "The western counties of Dickinson",
    " Gogebic",
    " Iron and Menominee",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Nebraska",
    "Central and eastern Nebraska",
    "North Dakota",
    "Entire state except southwest",
    "Oklahoma",
    "Entire state except Kenton",
    "South Dakota",
    "Eastern half",
    "Tennessee",
    "Counties located to the west of the counties of Scott",
    " Morgan",
    " Roane",
    " Rhea",
    " and Hamilton",
    "Texas",
    "Entire state except westernmost counties",
    "Wisconsin"
  ],
  "−05.00": [
    "Bahamas",
    "Brazil",
    "Acre",
    "Amazonas (13 western municipalities",
    " approximately marked by a line between Tabatinga and Porto Acre)",
    "Canada (Eastern Time Zone)",
    "Nunavut",
    "Qikiqtaaluk Region except Resolute",
    "Ontario",
    "East of 90° West except Big Trout Lake area",
    "Atikokan area",
    "New Osnaburgh and Pickle Lake area",
    "Upsala (West of 90° West)",
    "Quebec",
    "Most of province except easternmost area",
    "Colombia",
    "Cuba",
    "Ecuador",
    "Haiti",
    "Jamaica",
    "Panama",
    "Peru",
    "United Kingdom",
    "Cayman Islands",
    "Turks and Caicos Islands",
    "United States (Eastern Time Zone)",
    "Delaware",
    "District of Columbia",
    "Florida",
    "Except the western counties of Calhoun",
    " Gulf (northern part) and Jackson",
    " and all counties to the west of these",
    "Georgia",
    "Indiana",
    "Except the northwestern counties of Jasper",
    " Lake",
    " LaPorte",
    " Newton",
    " Porter and Starke",
    " and the southwestern counties of Gibson",
    " Perry",
    " Posey",
    " Spencer",
    " Vanderburgh and Warrick",
    "Kentucky",
    "Counties located to the east of the counties of Breckenridge",
    " Grayson",
    " Hart",
    " Green",
    " Adair",
    " Russell and Clinton",
    "Maryland",
    "Michigan",
    "Except the western counties of Dickinson",
    " Gogebic",
    " Iron and Menominee",
    "New England (states of Connecticut",
    " Massachusetts",
    " Maine",
    " New Hampshire",
    " Rhode Island and Vermont)",
    "New Jersey",
    "New York",
    "North Carolina",
    "Ohio",
    "Pennsylvania",
    "South Carolina",
    "Tennessee",
    "The counties of Scott",
    " Morgan",
    " Roane",
    " Rhea",
    " Meigs and Bradley",
    " and all counties to the east of these",
    "Virginia",
    "West Virginia",
    "United States Minor Outlying Islands",
    "Navassa Island"
  ],
  "−04.30": [
    "Venezuela"
  ],
  "−04.00": [
    "Antigua and Barbuda",
    "Barbados",
    "Bolivia",
    "Brazil",
    "The states of Amazonas (except westernmost municipalities)",
    " Mato Grosso",
    " Mato Grosso do Sul",
    "Rondônia and Roraima",
    "Canada (Atlantic Time Zone)",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Labrador",
    "Except the area between L'Anse-au-Clair and Norman Bay",
    "Nova Scotia",
    "Prince Edward Island",
    "Quebec",
    "East of the 63°W longitude",
    "Chile",
    "Denmark",
    "Greenland",
    "North-western area including Qaanaaq (Thule) and Pituffik",
    "Dominica",
    "Dominican Republic",
    "France",
    "Guadeloupe",
    "Martinique",
    "Saint Barthélemy",
    "Saint-Martin",
    "Grenada",
    "Guyana",
    "Netherlands",
    "Aruba",
    "Caribbean Netherlands",
    "Bonaire",
    "Saba",
    "Sint Eustatius",
    "Curaçao",
    "Sint Maarten",
    "Paraguay",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Trinidad and Tobago",
    "United Kingdom",
    "Anguilla",
    "Bermuda",
    "British Virgin Islands",
    "Montserrat",
    "United States (Atlantic Time Zone)",
    "Puerto Rico",
    "U.S. Virgin Islands"
  ],
  "−03.30": [
    "Canada (Newfoundland Time Zone)",
    "Newfoundland and Labrador",
    "Labrador",
    "The area between L'Anse-au-Clair and Norman Bay",
    "Newfoundland"
  ],
  "−03.00": [
    "Argentina",
    "Brazil",
    "Except the western states of Acre",
    " Amazonas",
    " Mato Grosso",
    " Mato Grosso do Sul",
    "Rondônia and Roraima; and offshore islands",
    "Denmark",
    "Greenland",
    "Except areas around Qaanaaq",
    " Danmarkshavn and Ittoqqortoormiit",
    "France",
    "French Guiana",
    "Saint-Pierre and Miquelon",
    "Suriname",
    "United Kingdom",
    "Falkland Islands",
    "Uruguay"
  ],
  "−02.00": [
    "Brazil",
    "Fernando de Noronha",
    "United Kingdom",
    "South Georgia and the South Sandwich Islands"
  ],
  "−01.00": [
    "Cape Verde",
    "Denmark",
    "Greenland",
    "Ittoqqortoormiit and surrounding area",
    "Portugal",
    "Azores islands"
  ],
  "±00.00": [
    "Burkina Faso",
    "Côte d'Ivoire",
    "Denmark",
    "Faroe Islands",
    "Greenland",
    "Danmarkshavn and surrounding area",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Iceland",
    "Ireland",
    "Liberia",
    "Mali",
    "Mauritania",
    "Morocco",
    "Portugal (Including Madeira and excluding Azores islands)",
    "Sahrawi Republic (limited recognition)",
    "São Tomé and Príncipe",
    "Spain",
    "Canary Islands",
    "Senegal",
    "Sierra Leone",
    "Togo",
    "United Kingdom (Including Guernsey",
    " Isle of Man",
    " Jersey and Saint Helena",
    "Ascension and Tristan da Cunha)"
  ],
  "+01.00": [
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Austria",
    "Belgium",
    "Benin",
    "Bosnia and Herzegovina",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Congo-Brazzaville",
    "Democratic Republic of the Congo",
    "The provinces of Bandundu",
    " Bas-Congo",
    "Équateur and Kinshasa",
    "Croatia",
    "Czech Republic",
    "Denmark",
    "Equatorial Guinea",
    "France",
    "Gabon",
    "Germany",
    "Hungary",
    "Italy",
    "Kosovo",
    "Liechtenstein",
    "Luxembourg",
    "Macedonia",
    "Malta",
    "Monaco",
    "Montenegro",
    "Namibia",
    "Netherlands",
    "Niger",
    "Nigeria",
    "Norway (Including Svalbard and Jan Mayen)",
    "Poland",
    "San Marino",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain (Including Balearic Islands",
    " Ceuta and Melilla and excluding Canary Islands)",
    "Sweden",
    "Switzerland",
    "Tunisia",
    "United Kingdom",
    "Gibraltar",
    "Vatican City"
  ],
  "+02.00": [
    "Botswana",
    "Bulgaria",
    "Burundi",
    "Cyprus (Including Northern Cyprus)",
    "Democratic Republic of the Congo",
    "The provinces of Kasaï Occidental",
    "Kasaï Oriental",
    " Katanga",
    " Maniema",
    " Nord-Kivu",
    " Orientale and Sud-Kivu",
    "Egypt",
    "Estonia",
    "Finland",
    "Greece",
    "Israel",
    "Jordan",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Lithuania",
    "Libya",
    "Malawi",
    "Moldova",
    "Mozambique",
    "Palestine",
    "Romania",
    "Rwanda",
    "South Africa",
    "Swaziland",
    "Syria",
    "Turkey",
    "Ukraine",
    "United Kingdom",
    "Akrotiri and Dhekelia",
    "Zambia",
    "Zimbabwe"
  ],
  "+03.00": [
    "Bahrain",
    "Belarus",
    "Comoros",
    "Djibouti",
    "Eritrea",
    "Ethiopia",
    "France",
    "French Southern and Antarctic Lands",
    "Scattered Islands in the Indian Ocean",
    "Bassas da India",
    " Europa Island and Juan de Nova Island",
    "Mayotte",
    "Iraq",
    "Kenya",
    "Kuwait",
    "Madagascar",
    "Qatar",
    "Russia",
    "Northwestern Federal District",
    "Kaliningrad Oblast",
    "Saudi Arabia",
    "Somalia",
    "South Africa",
    "Prince Edward Islands",
    "Southern Sudan",
    "Sudan",
    "Tanzania",
    "Uganda",
    "Yemen"
  ],
  "+03.30": [
    "Iran"
  ],
  "+04.00": [
    "Armenia",
    "Azerbaijan",
    "France",
    "French Southern and Antarctic Lands",
    "Crozet Islands",
    "Scattered Islands in the Indian Ocean",
    "Glorioso Islands and Tromelin Island",
    "Réunion",
    "Georgia",
    "Mauritius",
    "Oman",
    "Russia - Moscow Time",
    "Central Federal District",
    "North Caucasian Federal District",
    "Northwestern Federal District",
    "Except Kaliningrad Oblast",
    "Southern Federal District",
    "Volga Federal District",
    "Except Bashkortostan",
    " Orenburg Oblast and Perm Krai",
    "Seychelles",
    "United Arab Emirates"
  ],
  "+04.30": [
    "Afghanistan"
  ],
  "+05.00": [
    "Australia",
    "Heard Island and McDonald Islands",
    "France",
    "French Southern and Antarctic Lands",
    "Île Amsterdam",
    "Île Saint-Paul",
    "Kerguelen Islands",
    "Kazakhstan",
    "The provinces of Aktobe",
    " Atyrau",
    " Mangystau and West Kazakhstan",
    "Maldives",
    "Pakistan",
    "Tajikistan",
    "Turkmenistan",
    "Uzbekistan"
  ],
  "+05.30": [
    "India",
    "Sri Lanka"
  ],
  "+05.45": [
    "Nepal"
  ],
  "+06.00": [
    "Bangladesh",
    "Bhutan",
    "Kazakhstan",
    "Except the provinces of Aktobe",
    " Atyrau",
    " Mangystau and West Kazakhstan",
    "Kyrgyzstan",
    "Russia - Yekaterinburg Time",
    "Ural Federal District",
    "Volga Federal District",
    "Bashkortostan",
    " Orenburg Oblast and Perm Krai",
    "United Kingdom",
    "British Indian Ocean Territory"
  ],
  "+06.30": [
    "Australia",
    "Cocos (Keeling) Islands",
    "Myanmar"
  ],
  "+07.00": [
    "Australia",
    "Christmas Island",
    "Cambodia",
    "Indonesia",
    "Java",
    " Sumatra",
    " West Kalimantan and Central Kalimantan",
    "Laos",
    "Mongolia",
    "Western part",
    " including Hovd",
    "Russia - Omsk Time",
    "Siberian Federal District",
    "Altai Krai",
    "Altai Republic",
    "Kemerovo Oblast",
    "Novosibirsk Oblast",
    "Omsk Oblast",
    "Tomsk Oblast",
    "Thailand",
    "Vietnam"
  ],
  "+08.00": [
    "Australia",
    "Western Australia (except Eucla)",
    "Brunei",
    "China",
    "Indonesia",
    "East Kalimantan",
    " South Kalimantan",
    " Lesser Sunda Islands and Sulawesi",
    "Malaysia",
    "Mongolia",
    "Eastern part",
    " including Ulaanbaatar",
    "Philippines",
    "Russia - Krasnoyarsk Time",
    "Siberian Federal District",
    "Khakassia",
    "Krasnoyarsk Krai",
    "Tuva",
    "Singapore",
    "Taiwan"
  ],
  "+08.45": [
    "Australia",
    "Western Australia",
    "Eucla"
  ],
  "+09.00": [
    "Indonesia",
    "Maluku Islands",
    " Papua and West Papua",
    "Japan",
    "North Korea",
    "South Korea",
    "Palau",
    "Russia - Irkutsk Time",
    "Siberian Federal District",
    "Buryatia",
    "Irkutsk Oblast",
    "Timor-Leste"
  ],
  "+09.30": [
    "Australia",
    "Northern Territory and South Australia"
  ],
  "+10.00": [
    "Australia",
    "Australian Capital Territory",
    " New South Wales",
    " Queensland",
    " Tasmania and Victoria",
    "Federated States of Micronesia",
    "Chuuk State",
    "Yap State",
    "Papua New Guinea",
    "Russia",
    "Far Eastern Federal District",
    "Amur Oblast",
    " Zabaykalsky Krai and Sakha Republic (western part)",
    "United States",
    "Guam",
    "Northern Mariana Islands"
  ],
  "+10.30": [
    "Australia",
    "New South Wales",
    "Lord Howe Island"
  ],
  "+11.00": [
    "Federated States of Micronesia",
    "Kosrae State",
    "Pohnpei State",
    "France",
    "New Caledonia",
    "Russia - Vladivostok Time",
    "Far Eastern Federal District",
    "Primorsky Krai",
    " Jewish Autonomous Oblast",
    " Khabarovsk Krai",
    " Sakha Republic (central part)",
    " Sakhalin Island",
    "Solomon Islands",
    "Vanuatu"
  ],
  "+11.30": [
    "Australia",
    "Norfolk Island"
  ],
  "+12.00": [
    "Antarctica",
    "Ross Dependency",
    " McMurdo Station",
    " Amundsen-Scott South Pole Station (Unofficial)",
    "France",
    "Wallis and Futuna",
    "Fiji",
    "Kiribati",
    "Gilbert Islands",
    "Marshall Islands",
    "Nauru",
    "New Zealand (except Chatham Islands)",
    "Russia - Magadan Time",
    "Far Eastern Federal District",
    "Chukotka Autonomous Okrug",
    " Kamchatka Krai",
    " Magadan Oblast",
    " Sakha Republic (eastern part)",
    " Kuril Islands",
    "Tuvalu",
    "United States",
    "Wake Island"
  ],
  "+12.45": [
    "New Zealand",
    "Chatham Islands"
  ],
  "+13.00": [
    "Kiribati",
    "Phoenix Islands",
    "New Zealand",
    "Tokelau",
    "Samoa",
    "Tonga"
  ],
  "+14.00": [
    "Kiribati",
    "Line Islands"
  ]
}