var timezones = {
  "-12.00": [
    "United States Minor Outlying Islands",
    "Baker Island",
    "Howland Island"
  ],
  "-11.00": [
    "American Samoa",
    "Hawaii",
    "French Frigate Shoals and all of the Northwestern Hawaiian Islands located further west",
    "United States Minor Outlying Islands",
    "Jarvis Island",
    "Kingman Reef",
    "Midway Atoll",
    "Palmyra Atoll",
    "New Zealand",
    "Niue"
  ],
  "-10.00": [
    "French Polynesia (except Marquesas Islands and Gambier Islands)",
    "New Zealand",
    "Cook Islands",
    "Alaska",
    "Aleutian Islands west of 169.30°W",
    "Hawaii",
    "As far west as Necker Island",
    "United States Minor Outlying Islands",
    "Johnston Atoll"
  ],
  "-9.30": [
    "French Polynesia",
    "Marquesas Islands"
  ],
  "-9.00": [
    "French Polynesia",
    "Gambier Islands",
    "Alaska",
  ],
  "-8.00": [
    "Canada (Pacific Time Zone)",
    "British Columbia",
    " Golden and Invermere",
    "Yukon",
    "France",
    "Clipperton Island",
    "Mexico",
    "Baja California",
    "Pitcairn Islands",
    "United States (Pacific Time Zone)",
    "California",
    "Idaho",
    "Nevada (except West Wendover)",
    "Oregon",
    "Washington"
  ],
  "-7.00": [
    "Alberta",
    "British Columbia",
    "The south-eastern communities of Cranbrook",
    " Golden and Invermere",
    "Northwest Territories",
    "Nunavut",
    "Kitikmeot Region",
    "Saskatchewan",
    "Lloydminster",
    "Mexico",
    "Baja California Sur",
    " Chihuahua",
    " Nayarit",
    " Sinaloa and Sonora states",
    "Arizona",
    "Colorado",
    "Idaho",
    "South of Salmon River",
    "Kansas",
    "Montana",
    "Nebraska",
    "Nevada",
    "West Wendover",
    "New Mexico",
    "North Dakota",
    "Oregon",
    "Texas",
    "Utah",
    "Wyoming"
  ],
  "-6.00": [
    "Belize",
    "Canada (Central Time Zone)",
    "Manitoba",
    "Nunavut",
    "Kivalliq Region except Southampton Island (Coral Harbour)",
    "Saskatchewan",
    "Chile",
    "Easter Island",
    "Costa Rica",
    "Ecuador",
    "Galápagos Islands",
    "El Salvador",
    "Guatemala",
    "Honduras",
    "Mexico",
    "Sinaloa and Sonora.",
    "Nicaragua",
    "United States (Central Time Zone)",
    "Alabama",
    "Arkansas",
    "Florida",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Nebraska",
    "Central and eastern Nebraska",
    "North Dakota",
    "Oklahoma",
    "South Dakota",
    "Eastern half",
    "Tennessee",
    "Texas",
    "Wisconsin"
  ],
  "-5.00": [
    "Bahamas",
    "Brazil",
    "Acre",
    "Amazonas (13 western municipalities",
    "Nunavut",
    "Qikiqtaaluk Region except Resolute",
    "Ontario",
    "Quebec",
    "Colombia",
    "Cuba",
    "Ecuador",
    "Haiti",
    "Jamaica",
    "Panama",
    "Peru",
    "United Kingdom",
    "Cayman Islands",
    "Turks and Caicos Islands",
    "United States (Eastern Time Zone)",
    "Delaware",
    "District of Columbia",
    "Florida",
    "Georgia",
    "Indiana",
    "Kentucky",
    "Maryland",
    "Michigan",
    " Massachusetts",
    " Maine",
    " New Hampshire",
    " Rhode Island and Vermont)",
    "New Jersey",
    "New York",
    "North Carolina",
    "Ohio",
    "Pennsylvania",
    "South Carolina",
    "Tennessee",
    "Virginia",
    "West Virginia",
    "Navassa Island"
  ],
  "-4.30": [
    "Venezuela"
  ],
  "-4.00": [
    "Antigua and Barbuda",
    "Barbados",
    "Bolivia",
    "Brazil",
    " Mato Grosso",
    " Mato Grosso do Sul",
    "Rondônia and Roraima",
    "Canada (Atlantic Time Zone)",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Labrador",
    "Nova Scotia",
    "Prince Edward Island",
    "Quebec",
    "Chile",
    "Denmark",
    "Greenland",
    "Dominica",
    "Dominican Republic",
    "France",
    "Guadeloupe",
    "Martinique",
    "Saint Barthélemy",
    "Saint-Martin",
    "Grenada",
    "Guyana",
    "Netherlands",
    "Aruba",
    "Caribbean Netherlands",
    "Bonaire",
    "Saba",
    "Sint Eustatius",
    "Curaçao",
    "Sint Maarten",
    "Paraguay",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Trinidad and Tobago",
    "United Kingdom",
    "Anguilla",
    "Bermuda",
    "British Virgin Islands",
    "Montserrat",
    "United States (Atlantic Time Zone)",
    "Puerto Rico",
    "U.S. Virgin Islands"
  ],
  "-3.30": [
    "Canada (Newfoundland Time Zone)",
    "Newfoundland and Labrador",
    "Labrador",
    "The area between L'Anse-au-Clair and Norman Bay",
    "Newfoundland"
  ],
  "-3.00": [
    "Argentina",
    "Brazil",
    "Rondônia and Roraima; and offshore islands",
    "Denmark",
    "Greenland",
    " Danmarkshavn and Ittoqqortoormiit",
    "French Guiana",
    "Saint-Pierre and Miquelon",
    "Suriname",
    "Falkland Islands",
    "Uruguay"
  ],
  "-2.00": [
    "Brazil",
    "United Kingdom",
    "South Georgia and the South Sandwich Islands"
  ],
  "-1.00": [
    "Cape Verde",
    "Denmark",
    "Greenland",
    "Ittoqqortoormiit and surrounding area",
    "Portugal",
    "Azores islands"
  ],
  "0.00": [
    "Burkina Faso",
    "Côte d'Ivoire",
    "Denmark",
    "Faroe Islands",
    "Greenland",
    "Danmarkshavn and surrounding area",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Iceland",
    "Ireland",
    "Liberia",
    "Mali",
    "Mauritania",
    "Morocco",
    "Portugal (Including Madeira and excluding Azores islands)",
    "Sahrawi Republic (limited recognition)",
    "São Tomé and Príncipe",
    "Spain",
    "Canary Islands",
    "Senegal",
    "Sierra Leone",
    "Togo",
    "United Kingdom (Including Guernsey",
    " Isle of Man",
    " Jersey and Saint Helena",
    "Ascension and Tristan da Cunha)"
  ],
  "1.00": [
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Austria",
    "Belgium",
    "Benin",
    "Bosnia and Herzegovina",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Congo-Brazzaville",
    "Democratic Republic of the Congo",
    "The provinces of Bandundu",
    " Bas-Congo",
    "Équateur and Kinshasa",
    "Croatia",
    "Czech Republic",
    "Denmark",
    "Equatorial Guinea",
    "France",
    "Gabon",
    "Germany",
    "Hungary",
    "Italy",
    "Kosovo",
    "Liechtenstein",
    "Luxembourg",
    "Macedonia",
    "Malta",
    "Monaco",
    "Montenegro",
    "Namibia",
    "Netherlands",
    "Niger",
    "Nigeria",
    "Norway (Including Svalbard and Jan Mayen)",
    "Poland",
    "San Marino",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain (Including Balearic Islands",
    " Ceuta and Melilla and excluding Canary Islands)",
    "Sweden",
    "Switzerland",
    "Tunisia",
    "United Kingdom",
    "Gibraltar",
    "Vatican City"
  ],
  "2.00": [
    "Botswana",
    "Bulgaria",
    "Burundi",
    "Cyprus (Including Northern Cyprus)",
    "Democratic Republic of the Congo",
    "The provinces of Kasaï Occidental",
    "Kasaï Oriental",
    " Katanga",
    " Maniema",
    " Nord-Kivu",
    " Orientale and Sud-Kivu",
    "Egypt",
    "Estonia",
    "Finland",
    "Greece",
    "Israel",
    "Jordan",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Lithuania",
    "Libya",
    "Malawi",
    "Moldova",
    "Mozambique",
    "Palestine",
    "Romania",
    "Rwanda",
    "South Africa",
    "Swaziland",
    "Syria",
    "Turkey",
    "Ukraine",
    "United Kingdom",
    "Akrotiri and Dhekelia",
    "Zambia",
    "Zimbabwe"
  ],
  "3.00": [
    "Bahrain",
    "Belarus",
    "Comoros",
    "Djibouti",
    "Eritrea",
    "Ethiopia",
    "France",
    "French Southern and Antarctic Lands",
    "Scattered Islands in the Indian Ocean",
    "Bassas da India",
    " Europa Island and Juan de Nova Island",
    "Mayotte",
    "Iraq",
    "Kenya",
    "Kuwait",
    "Madagascar",
    "Qatar",
    "Russia",
    "Northwestern Federal District",
    "Kaliningrad Oblast",
    "Saudi Arabia",
    "Somalia",
    "South Africa",
    "Prince Edward Islands",
    "Southern Sudan",
    "Sudan",
    "Tanzania",
    "Uganda",
    "Yemen"
  ],
  "3.30": [
    "Iran"
  ],
  "4.00": [
    "Armenia",
    "Azerbaijan",
    "France",
    "French Southern and Antarctic Lands",
    "Crozet Islands",
    "Scattered Islands in the Indian Ocean",
    "Glorioso Islands and Tromelin Island",
    "Réunion",
    "Georgia",
    "Mauritius",
    "Oman",
    "Russia - Moscow Time",
    "Central Federal District",
    "North Caucasian Federal District",
    "Northwestern Federal District",
    "Except Kaliningrad Oblast",
    "Southern Federal District",
    "Volga Federal District",
    "Except Bashkortostan",
    " Orenburg Oblast and Perm Krai",
    "Seychelles",
    "United Arab Emirates"
  ],
  "4.30": [
    "Afghanistan"
  ],
  "5.00": [
    "Australia",
    "Heard Island and McDonald Islands",
    "France",
    "French Southern and Antarctic Lands",
    "Île Amsterdam",
    "Île Saint-Paul",
    "Kerguelen Islands",
    "Kazakhstan",
    "The provinces of Aktobe",
    " Atyrau",
    " Mangystau and West Kazakhstan",
    "Maldives",
    "Pakistan",
    "Tajikistan",
    "Turkmenistan",
    "Uzbekistan"
  ],
  "5.30": [
    "India",
    "Sri Lanka"
  ],
  "5.45": [
    "Nepal"
  ],
  "6.00": [
    "Bangladesh",
    "Bhutan",
    "Kazakhstan",
    "Except the provinces of Aktobe",
    " Atyrau",
    " Mangystau and West Kazakhstan",
    "Kyrgyzstan",
    "Russia - Yekaterinburg Time",
    "Ural Federal District",
    "Volga Federal District",
    "Bashkortostan",
    " Orenburg Oblast and Perm Krai",
    "United Kingdom",
    "British Indian Ocean Territory"
  ],
  "6.30": [
    "Australia",
    "Cocos (Keeling) Islands",
    "Myanmar"
  ],
  "7.00": [
    "Australia",
    "Christmas Island",
    "Cambodia",
    "Indonesia",
    "Java",
    " Sumatra",
    " West Kalimantan and Central Kalimantan",
    "Laos",
    "Mongolia",
    "Western part",
    " including Hovd",
    "Russia - Omsk Time",
    "Siberian Federal District",
    "Altai Krai",
    "Altai Republic",
    "Kemerovo Oblast",
    "Novosibirsk Oblast",
    "Omsk Oblast",
    "Tomsk Oblast",
    "Thailand",
    "Vietnam"
  ],
  "8.00": [
    "Australia",
    "Western Australia (except Eucla)",
    "Brunei",
    "China",
    "Indonesia",
    "East Kalimantan",
    " South Kalimantan",
    " Lesser Sunda Islands and Sulawesi",
    "Malaysia",
    "Mongolia",
    "Eastern part",
    " including Ulaanbaatar",
    "Philippines",
    "Russia - Krasnoyarsk Time",
    "Siberian Federal District",
    "Khakassia",
    "Krasnoyarsk Krai",
    "Tuva",
    "Singapore",
    "Taiwan"
  ],
  "8.45": [
    "Australia",
    "Western Australia",
    "Eucla"
  ],
  "9.00": [
    "Indonesia",
    "Maluku Islands",
    " Papua and West Papua",
    "Japan",
    "North Korea",
    "South Korea",
    "Palau",
    "Russia - Irkutsk Time",
    "Siberian Federal District",
    "Buryatia",
    "Irkutsk Oblast",
    "Timor-Leste"
  ],
  "9.30": [
    "Australia",
    "Northern Territory and South Australia"
  ],
  "10.00": [
    "Australia",
    "Australian Capital Territory",
    " New South Wales",
    " Queensland",
    " Tasmania and Victoria",
    "Federated States of Micronesia",
    "Chuuk State",
    "Yap State",
    "Papua New Guinea",
    "Russia",
    "Far Eastern Federal District",
    "Amur Oblast",
    " Zabaykalsky Krai and Sakha Republic (western part)",
    "United States",
    "Guam",
    "Northern Mariana Islands"
  ],
  "10.30": [
    "Australia",
    "New South Wales",
    "Lord Howe Island"
  ],
  "11.00": [
    "Federated States of Micronesia",
    "Kosrae State",
    "Pohnpei State",
    "France",
    "New Caledonia",
    "Russia - Vladivostok Time",
    "Far Eastern Federal District",
    "Primorsky Krai",
    " Jewish Autonomous Oblast",
    " Khabarovsk Krai",
    " Sakha Republic (central part)",
    " Sakhalin Island",
    "Solomon Islands",
    "Vanuatu"
  ],
  "11.30": [
    "Australia",
    "Norfolk Island"
  ],
  "12.00": [
    "Antarctica",
    "Ross Dependency",
    " McMurdo Station",
    " Amundsen-Scott South Pole Station (Unofficial)",
    "France",
    "Wallis and Futuna",
    "Fiji",
    "Kiribati",
    "Gilbert Islands",
    "Marshall Islands",
    "Nauru",
    "New Zealand (except Chatham Islands)",
    "Russia - Magadan Time",
    "Far Eastern Federal District",
    "Chukotka Autonomous Okrug",
    " Kamchatka Krai",
    " Magadan Oblast",
    " Sakha Republic (eastern part)",
    " Kuril Islands",
    "Tuvalu",
    "United States",
    "Wake Island"
  ],
  "12.45": [
    "New Zealand",
    "Chatham Islands"
  ],
  "13.00": [
    "Kiribati",
    "Phoenix Islands",
    "New Zealand",
    "Tokelau",
    "Samoa",
    "Tonga"
  ],
  "14.00": [
    "Kiribati",
    "Line Islands"
  ]
}